### ISSUE TITLE
What does reloadTasks do with regard to __coverage__?

### ISSUE THREAD

**Issue by wheresrhys** [taichi/grunt-istanbul#16]
I'm trying to implement an istanbul report on code that's bundled using browserify, using the approach recommended here https://github.com/gotwarlost/istanbul/issues/59#issuecomment-18799734. I've completed every recommended step (I instrument my src, bundle it, then bundle my test files and get them to reference the instrumented src bundle), but using grunt-istanbul ,my reports are always empty.

If I run `reloadTasks` on my instrumented src files (as you do in your gruntfile) then I do get a report, but it evidently doesn't use my bundled, instrumented src as the results show no code was run even though all the tests run and pass. If I don't run reloadTasks I get `Fatal error: No coverage information was collected` when running `storeCoverage`.

All the code is here https://github.com/wheresrhys/on-guard/tree/browserify (note that it's the 'browserify' branch)

**Comment by reefath** [comment]
Is anyone successful in using this package without 'reloadTasks'? I get the error
Running "storeCoverage" task
Fatal error: No coverage information was collected

I'm trying to get the coverage report for server side ES5 files in a node JS project that uses Grunt for build. Even if I add grunt task for 'reloadTasks' there are lot of errors on the dependencies. Any help is appreciated!

**Comment by robertgroh** [comment]
@reefath,
no `reloadTasks` is need for normal test coverage - it is only used to test `grunt-istanbul` itself.

As I stated above (quoting myself: https://github.com/taichi/grunt-istanbul/issues/16#issuecomment-48204815), either:
> *  your test don't use the instrumented files during the coverage run, or
> * your tests are run by a other process as the grunt tasks

> Istanbul instruments the src files in such a way, that they write the coverage information in a global variable (default: coverage), during their execution.
The value of this global variable can then be write to a .json file by the task storeCoverage.
And with the makeReport task, you generate the coverage report in different formats (lcov, html, cobertura) out of the .json files.

> Therefore the test run have to use the instrumented files instead of the normal source files (file path for require() statements - show us your test files). And also the step, when you want to write out the coverage information to .json files, you have to be in the same process as the test run, to access the global variable __coverage__.

For further help please provide your gruntfile (as a new issue with more details).

@wheresrhys & @taichi: I think this issue can & should be closed.
