### ISSUE TITLE
looks like 'instrument' is broken

### ISSUE THREAD

**Issue by miranda820** [taichi/grunt-istanbul#31]
In my package.js it's listed I'm using
"grunt-istanbul": "^0.4.0"

When I run `grunt coverage` I get
**Running "instrument" task**
**Fatal error: Cannot read property 'instrument' of undefined**
Looks like instrument task is not generating instrument code. When I change **grunt-istanbul** to **0.3.0** everything works as expected.

**Comment by ali-bugdayci** [comment]
Hi,

Got the same error. I debuged and saw that its coming from the following line:

https://github.com/taichi/grunt-istanbul/blob/master/tasks/helpers.js#L98

Then I update it with the following code:
```
          if (f && f.instrument) {
```

But this time I am getting the following error:

```
Fatal error: An error occurred in an async call.
cause stack is ...
  Error: ENOENT, stat 'instrumented/server.js'
async call history is ...
 [ { function: 'readStat',
    location: '/home/bor/sunucu/mdm-server/node_modules/grunt-istanbul/tasks/helpers.js:88:43',
    mapping: { name: 'server.js', stat: [Object] } } ]

```

**Comment by LoicMahieu** [comment]
I got the same. Rollback to 0.3.0

**Comment by langma** [comment]
For me, setting ```lazy: false``` for instrument task makes it run successfully. So the problem is probably in the lazy handling...
