### ISSUE TITLE
grunt-istanbul 0.4.0 install failure

### ISSUE THREAD

**Issue by nishantmc** [taichi/grunt-istanbul#32]
npm install grunt-istanbul@0.4.0
npm ERR! Error: version not found: nue@0.7.0-dev
npm ERR!     at /auto/irelease/apps/node-v0.10.29-linux-x64/lib/node_modules/npm/lib/cache/add-named.js:123:12
npm ERR!     at saved (/auto/irelease/apps/node-v0.10.29-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:141:7)
npm ERR!     at /auto/irelease/apps/node-v0.10.29-linux-x64/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by mrfelton** [comment]
Also suddenly started getting this

**Comment by taichi** [comment]
nue 0.7.0-dev is exists. please retry.

**Comment by mrfelton** [comment]
exists where? https://github.com/nakamura-to/nue/releases

**Comment by taichi** [comment]
here https://www.npmjs.com/package/nue

**Comment by masotime** [comment]
The link points to a `0.70dev` rather than `0.70-dev` [image](http://i4.minus.com/ibjAMb1wqKJ3M2.png)

**Comment by taichi** [comment]
see. http://registry.npmjs.org/nue/0.7.0-dev

**Comment by prabhu** [comment]
http://registry.npmjs.org/nue doesn't point the hyphen version at all. Can you fix this please?

**Comment by taichi** [comment]
sure.

**Comment by taichi** [comment]
0.4.1 released.

**Comment by prabhu** [comment]
Thank you!
