### ISSUE TITLE
Exclude files for coverage

### ISSUE THREAD

**Issue by supritashankar** [taichi/grunt-istanbul#46]
How do I configure my code coverage to exclude files for coverage?

My coverage looks like this now

`codecoverage: {
         all: {
                src: serverSource,
                options: {
                    timeout: 20000,
                    ignoreLeaks: false,
                    ui: 'bdd',
                    reporter: 'dot',
                    covDir: coverageDirectory + '/istanbul',
                    reportType: 'lcov',
                    printType: 'both'
                }
            }
        },`

I want to exclude a particular file from coverage. Can someone please share how do I do so?

Thanks!

**Comment by gregglind** [comment]
Change the `files` list.

example:
```
            files: ['lib/**/*.js', '!lib/some-excluded.js'],
````

See: http://gruntjs.com/api/grunt.file#grunt.file.expand
