### ISSUE TITLE
Please upgrade your "istanbul" dependency version

### ISSUE THREAD

**Issue by JamesMGreene** [taichi/grunt-istanbul#48]
Please upgrade your "istanbul" dependency version to at least `0.4.4` (currently set at `0.4.2`), or else allow for a version range (e.g. `0.4.x`, `~0.4.2`, `^0.4.2`, etc.) so that your wrapper can keep up with the underlying dependencies' non-breaking changes.

**Comment by JamesMGreene** [comment]
_\*ping\*_

**Comment by taichi** [comment]
*pong*. i fixed. this issue.
