### ISSUE TITLE
Is there a way to generate multiple types of test reports?

### ISSUE THREAD

**Issue by scheibinger** [taichi/grunt-istanbul#52]
Is there a way to generate multiple test reports in the `makeReport` task?
I would like to generate lcov and cobertura reports at the same time.

**Comment by robertgroh** [comment]
I didn't test it, but there seems to be to ways:

1. The Plugin [accepts an Array of Strings](https://github.com/taichi/grunt-istanbul/blob/a39435278b328a7cdb889409154c8d8757c97e5e/tasks/helpers.js#L38) at the `type` property of the makeReport options:
```
    makeReport: {
      src: 'test/coverage/reports/**/*.json',
      options: {
        type: ['lcov', 'çobertura']
        dir: 'test/coverage/reports',
        print: 'detail'
      }
    }
```

2. It also seem to [accept an `reporters` property](https://github.com/taichi/grunt-istanbul/blob/a39435278b328a7cdb889409154c8d8757c97e5e/tasks/helpers.js#L24), which should have properties named after the report type:
```
    makeReport: {
      src: 'test/coverage/reports/**/*.json',
      options: {
        reporters: {
           lcov: { dir: 'test/coverage/lcov_report' }
           cobertura: { dir: 'test/coverage/cobertura_reports' }
        }
      }
    }
```
With the second way, you can set different options for each reporter.

It would be nice, if you could test both variants and maybe create a pull request with some documentation lines of this options for the README.md

**Comment by scheibinger** [comment]
thanks a lot @robertgroh I tried the second option with `reporters`, and it works for me!
